name: robenmarie
favicon: null
layout_spectrum: 0.83923
typography_spectrum: 0.5355123314075172
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d7e3d5'
    - '#a7beae'
    - '#7f9e98'
    - '#486666'
    - '#190b0a'
  brandStrength: 0.375
  lightness: 0.29682967462576926
  saturation: 0.75
  rhythmicContrast: 0.05981048080138862
purpose: []
