name: robenmarie
favicon: null
layout_spectrum: 0.6187153172213584
typography_spectrum: 0.5355123314075172
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d7cbb7'
    - '#fbfbfb'
    - '#cd6e1d'
    - '#080404'
    - '#4b3216'
  brandStrength: 0.375
  lightness: 0.29682967462576926
  saturation: 0.9313476977404207
  rhythmicContrast: 0.05981048080138862
purpose: []
