name: robenmarie
favicon: null
layout_spectrum: 0.69726
typography_spectrum: 0.52446
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d7e3d5'
    - '#a7beae'
    - '#7f9e98'
    - '#486666'
    - '#190b0a'
  brandStrength: 0.375
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
